# Site settings
title: "Krishna's Blog"
description: "Collections of my learnings"
url: "https://krishnamohan-seelam.github.io"
baseurl: "/my-blog"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/

# Include
include:
  - _pages